title: Samyu's Website
author: Samyuktha Minupala
email: sminupala@ebnet.org
description: > # this means to ignore newlines until "baseurl:"
  Why I'm the most amazing person ever

# social links
twitter_username: your-twitter-handle # DO NOT include the @ character, or else the build will fail!
github_username:  Samyu-08 # DO NOT include the @ character, or else the build will fail!
instagram_username: samyu_sa2

show_excerpts: true # set to false to remove excerpts on the homepage
theme: jekyll-theme-slate
